pass gitwebUrl into "version_link" translation
i love how failing to translate a string causes the
whole page to unload itself ToT

Error: The intl string context variable "gitwebURL" was not provided to the string "'<'a href="{ gitwebURL }"'>' Version: { version } Build: { build } '</a>'"